name: Refresh Daily Quote

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Daily Quote
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Quote and Update README
        run: |
          RAW_DATA=$(curl -s https://zenquotes.io/api/random)
          QUOTE_ONLY=$(echo "$RAW_DATA" | jq -r '.[0].q')
          AUTHOR_ONLY=$(echo "$RAW_DATA" | jq -r '.[0].a')
          
          python3 -c "
          import re
          
          quote = '''$QUOTE_ONLY'''
          author = '''$AUTHOR_ONLY'''
          
          with open('README.md', 'r') as f:
              content = f.read()
          
          pattern = r'<!-- DAILY_QUOTE:START -->[\s\S]*?<!-- DAILY_QUOTE:END -->'
          
          formatted_text = '🗯 Daily Quote :\n<center>$$\\color{#0c7ec9}{\\text{' + quote + '}}$$<br/>— $$\\color{#808080}{\\text{' + author + '}}$$</center>'
          replacement = '<!-- DAILY_QUOTE:START -->\n' + formatted_text + '\n<!-- DAILY_QUOTE:END -->'
          
          new_content = re.sub(pattern, replacement, content)
          
          with open('README.md', 'w') as f:
              f.write(new_content)
          "
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || (git commit -m "chore: update styled daily quote" && git push)
